disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - modifier_order
  - closure_spacing
  - contains_over_filter_is_empty
  - discouraged_object_literal
  - empty_collection_literal
  - empty_string
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - unneeded_parentheses_in_closure_argument

excluded:
  - DerivedData
  - .build
  - build
  - "*/DerivedSources/*"
  - "**/*.generated.swift"

identifier_name:
  min_length: 1
  excluded:
    - id
    - x
    - y
    - i
    - j

type_name:
  min_length: 2

nesting:
  type_level: 2
  function_level: 3

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 750
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: xcode
