name: QuarryMenuBar

options:
  bundleIdPrefix: com.puntlabs
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  defaultConfig: Debug
  developmentLanguage: en

packages:
  HighlightSwift:
    url: https://github.com/jmf-pobox/HighlightSwift
    from: "1.1.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "0.5.0"
    CURRENT_PROJECT_VERSION: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  QuarryMenuBar:
    type: application
    platform: macOS
    sources:
      - path: QuarryMenuBar
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: HighlightSwift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.puntlabs.quarry-menubar
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_LSUIElement: YES
        CODE_SIGN_ENTITLEMENTS: QuarryMenuBar/Resources/QuarryMenuBar.entitlements
    info:
      path: QuarryMenuBar/Info.plist
      properties:
        CFBundleDisplayName: Quarry
        LSMinimumSystemVersion: "14.0"
        ITSAppUsesNonExemptEncryption: false
    entitlements:
      path: QuarryMenuBar/Resources/QuarryMenuBar.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true

  QuarryMenuBarTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: QuarryMenuBarTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: QuarryMenuBar
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.puntlabs.quarry-menubar.tests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  QuarryMenuBar:
    build:
      targets:
        QuarryMenuBar: all
        QuarryMenuBarTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - QuarryMenuBarTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
